GET http://localhost:8000/profile/048d8c7b-40d6-49e9-8d74-3c793fa8f8a7 
Authorization: Bearer eyJhbGciOiJFUzI1NiIsImtpZCI6ImQzNTg2MTBkLWQxMGYtNGMwNC1iZGZiLTNkOGViZTRiOGE1MiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2luYWp4dHl4b2J6bWlmeHB2b25tLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiIwNDhkOGM3Yi00MGQ2LTQ5ZTktOGQ3NC0zYzc5M2ZhOGY4YTciLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzgxMjQyMjkzLCJpYXQiOjE3ODEyMzg2OTMsImVtYWlsIjoic2FuZGVzaGdoYXJnZTI3QGdtYWlsLmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiZW1haWxfdmVyaWZpZWQiOnRydWV9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzgxMjM4NjkzfV0sInNlc3Npb25faWQiOiI5MWExNTM4Ny1hOWYyLTRlYzctYTE3ZC03NzFkMmNkMTNjOTciLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.jP_NJeotSGZuhfsufs-0QsK6Ur8UBGws6SoeQlUcHigonfzQ1eEiX4_4am_j3w-JrtNsZzQQbeDcPtP8ejuJdw